// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLwFd7obI8KuJqhe7L4N1OZFGhuzfhn2A',
    appId: '1:73309775864:web:1811fef35274404d5f180d',
    messagingSenderId: '73309775864',
    projectId: 'customlogin-a5c54',
    authDomain: 'customlogin-a5c54.firebaseapp.com',
    storageBucket: 'customlogin-a5c54.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh3d4rlMNG9jkOkDfwfHmbl-028K6iGkE',
    appId: '1:73309775864:android:72f311cab648d7d55f180d',
    messagingSenderId: '73309775864',
    projectId: 'customlogin-a5c54',
    storageBucket: 'customlogin-a5c54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSbwHNkA5qviKMiqWP0lpSFTltq3P2Oss',
    appId: '1:73309775864:ios:0f088a80549523d15f180d',
    messagingSenderId: '73309775864',
    projectId: 'customlogin-a5c54',
    storageBucket: 'customlogin-a5c54.firebasestorage.app',
    iosBundleId: 'com.example.customlogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSbwHNkA5qviKMiqWP0lpSFTltq3P2Oss',
    appId: '1:73309775864:ios:0f088a80549523d15f180d',
    messagingSenderId: '73309775864',
    projectId: 'customlogin-a5c54',
    storageBucket: 'customlogin-a5c54.firebasestorage.app',
    iosBundleId: 'com.example.customlogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLwFd7obI8KuJqhe7L4N1OZFGhuzfhn2A',
    appId: '1:73309775864:web:f35de180ca4f04d55f180d',
    messagingSenderId: '73309775864',
    projectId: 'customlogin-a5c54',
    authDomain: 'customlogin-a5c54.firebaseapp.com',
    storageBucket: 'customlogin-a5c54.firebasestorage.app',
  );
}
